version: "3.8"

services:
  api:
    image: heartdiseaseapp.azurecr.io/heardisease-api:latest
    ports:
      - "81:8000"

  front:
    depends_on: 
      - api
    restart: always
    build:
       context: frontend
       dockerfile: Dockerfile
    image: heartdiseaseapp.azurecr.io/heartdisease-front:latest
    ports:
      - "80:80"
