name: Batch inference
run-name: Batch inference and store in Azure Blob Storage

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

env:
  WORKSPACE: ${{ secrets.WORKSPACE }} 
  WORKSPACE_LOCATION: ${{ secrets.WORKSPACE_LOCATION }} 
  SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }} 
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 

jobs:
  batch_inference:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
      - name: Run batch inference
        run:
          python batch_service/batch_service.py 