name: CI/CD pipeline
run-name: CI/CD pipeline

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: heartdiseaseapp

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      # - name: Install dependencies
      #   run: 
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: Run tests
      #   run: python -m pytest ./tests
  azure-container:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repo
      #   uses: actions/checkout@v3
      # - name: Setup QEMU
      #   uses: docker/setup-qemu-action@v2
      # - name: Build the Docker image
      #   run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  